# Generated by Django 4.2.1 on 2023-06-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
