# Generated by Django 4.2.1 on 2023-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_ordermodel_name_ordermodel_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
